### PR TITLE
Avoid requiring babel-loader in poi-preset-coffee if...

### PR DESCRIPTION
**Pull request by kirbyfan64**
!loaderOptions.transpile

Basically, without this, I could be like:

```javascript
module.exports = (options, req) => ({
  // ...
  presets: [
    require('poi-preset-coffee')({ loaderOptions: { transpile: false } }),
  ]
})
```

and poi-preset-coffee would *still* end up trying to import *babel-loader*, even though I'm not going to use this. (For me, this is because I'm using Buble instead, so it's pointless to have babel-loader.)

### CODE REVIEW

**Comment by egoist** [comment]
actually with `{ loaderOptions: { transpile: false } }` the `coffeeOptions` would be `{ transpile: false }`

**Comment by egoist** [comment]
Hmm just released https://github.com/webpack-contrib/coffee-loader/commit/abaf49879c936113d566f1bd7a6ed034ed75b1c7 is not yet published on npm...

**Comment by kirbyfan64** [comment]
@egoist Ugh, this is what happens when I send in PRs with too little sleep...

TBH all I really want is a way to *not* transpile via Babel...

**Comment by egoist** [comment]
I might update [poi-preset-buble](https://github.com/egoist/poi/tree/master/packages/poi-preset-buble) to make `buble-loader` transform the code generated by `coffee-loader` and set `transpile` to `false`. But do you really want to use `buble` with `coffeescript`? `buble` can't even transform async function.

btw since `coffee-loader` doesn't support `transpile` option for now (not yet updated on npm), `babel` isn't actually used by `coffeescript`, so your app remains what it is (i.e. es6).

**Pull request closed without merging**
